version: '3.3'
services:
 db:
   image: mysql:8.0
   volumes:
     - db_vol:/var/lib/mysql
     - ./mysql-dump:/docker-entrypoint-initdb.d
   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: proyecto
     MYSQL_USER: userPrueba
     MYSQL_PASSWORD: 12345
   ports:
     - 3307:3306
 phpmyadmin:
  depends_on:
    - db
  image: phpmyadmin/phpmyadmin
  ports:
    - '8081:80'
  environment:
    PMA_HOST: db
    MYSQL_ROOT_PASSWORD: root
 web:
  build:
    context: .       
  depends_on:
    - db
  image: tomcat:10.0
  volumes:
          - ./target/Gestion_Proyectos.war:/usr/local/tomcat/webapps/Gestion_Proyectos.war
  ports:
    - '8080:8080'
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: proyecto
    MYSQL_USER: userPrueba
    MYSQL_PASSWORD: 12345
volumes:
  db_vol: 